Githubactions proba2 im crying

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,8 +20,16 @@ jobs:
       - name: Build with Maven
         run: |
           chmod +x ./mvnw
-          ./mvnw clean package -DskipTests 
-          ls -la target/
+          ./mvnw clean package
+          ls -la target/  # Проверка содержимого папки target
+
+      - name: Verify JAR exists
+        run: |
+          if [ ! -f "target/gift-service-0.0.1-SNAPSHOT.jar" ]; then
+            echo "Error: JAR file not found!"
+            ls -la target/
+            exit 1
+          fi
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
